### ISSUE TITLE
knowledge of `npm install -g` and `yarn global`

### ISSUE THREAD

**Issue by dherman** [volta-cli/rfcs#4]
Notion should retain control of the global executables installed by npm or yarn; they should always be shims. This means the npm and yarn shims should alter the behavior of `npm install -g` and `yarn global` to do the right thing with setting up/modifying shims.

**Comment by charlespierce** [comment]
We implemented this by intercepting and throwing an error when a user attempts to globally install, directing them to instead us `volta install <package>`
